Added LetsEncrypt functionality

diff --git a/ee-br-restore b/ee-br-restore
--- a/ee-br-restore
+++ b/ee-br-restore
@@ -40,35 +40,52 @@ check_config_file
 
 if [[ ! "${@#--skip-ee-install}" = "$@" ]]
 then
-	echo "${r}${b}Not [re-]installing EasyEngine as per | --skip-ee-install |...${x}"
+	echo "${r}${b}- Not [re-]installing EasyEngine as per | --skip-ee-install |...${x}"
 	echo
 	skip_ee_install=y
 fi
 
 if [[ ! "${@#--skip-backup}" = "$@" ]]
 then
-	echo "${r}${b}Skipping current sites backup as per | --skip-backup |...${x}"
+	echo "${r}${b}- Skipping current sites backup as per | --skip-backup |...${x}"
 	echo
 	skip_backup=y
 fi
 
 if [[ ! "${@#--delete-existing}" = "$@" ]]
 then
-	echo "${r}${b}Deleting any already existing site to restore without asking as per | --delete-existing |...${x}"
+	echo "${r}${b}- Deleting any already existing site to restore without asking as per | --delete-existing |...${x}"
 	echo
 	non_interactive_deletion=y
 fi
 
 if [[ ! "${@#--enable-php=y}" = "$@" ]]
 then
-	echo "${b}Activating PHP on any NON wordpress site to restore without asking as per | --enable-php=y |...${x}"
+	echo "${b}- Activating PHP on any NON wordpress site to restore without asking as per | --enable-php=y |...${x}"
 	echo
 	non_interactive_php=y
 elif [[ ! "${@#--enable-php=n}" = "$@" ]]
 then
-	echo "${b}NOT activating PHP on any NON wordpress site to restore without asking as per | --enable-php=n |...${x}"
+	echo "${b}- NOT activating PHP on any NON wordpress site to restore without asking as per | --enable-php=n |...${x}"
 	echo
 	non_interactive_php=n
+fi
+
+if [[ ! "${@#--activate_le=y}" = "$@" ]]
+then
+	echo "${b}- Provisioning LetsEncrypt TLS certificate for restored sites without asking as per | --enable-php=y |...${x}"
+	echo
+	non_interactive_le=y
+elif [[ ! "${@#--activate_le=o}" = "$@" ]]
+then
+	echo "${b}- Provisioning LetsEncrypt TLS certificate OPPORTUNISTICALLY for restored sites without asking as per | --enable-php=o |...${x}"
+	echo
+	non_interactive_le=o
+elif [[ ! "${@#--activate_le=n}" = "$@" ]]
+then
+	echo "${b}- NOT provisioning LetsEncrypt TLS certificate for restored sites without asking as per | --enable-php=n |...${x}"
+	echo
+	non_interactive_le=n
 fi
 
 ################################################################################
@@ -340,6 +357,7 @@ do
 						echo "${b}   Activating PHP on this site...${x}"
 						echo
 						ee site update $this_site --php
+						echo
 
 					elif [ "${non_interactive_php:-null}" = "n" ]
 					then
@@ -356,6 +374,7 @@ do
 							echo
 							ee site update $this_site --php
 							echo
+							echo
 						else
 							echo
 							echo "${b}   Ok, skipping...${x}"
@@ -367,6 +386,284 @@ do
 				fi
 
 				rsync -aAXx --exclude wp-config.php "$site"/ "$www_site_dir"
+
+				if [ "${non_interactive_le:-null}" = "y" ]
+				then
+					echo "${b}   Provisioning LetsEncrypt TLS certificate for restored site...${x}"
+					echo
+					activate_le_proceed=y
+				elif [ "${non_interactive_le:-null}" = "o" ]
+				then
+					echo "${b}   Provisioning LetsEncrypt TLS certificate for restored site if DNS checks succeed...${x}"
+					echo
+					activate_le_proceed=o
+				elif [ "${non_interactive_le:-null}" = "n" ]
+				then
+					echo "${b}   NOT provisioning LetsEncrypt TLS certificate for restored site...${x}"
+					echo
+				else
+					read -rp "${b}   Also provision LetsEncrypt TLS certificate for restored site? (Y/n): ${x}" -n 1
+					echo
+					if [[ ! $REPLY =~ ^[Nn]$ ]]
+					then
+						echo "${b}   Ok, proceeding...${x}"
+						echo
+						activate_le_proceed=y
+					else
+						echo
+						echo "${b}   Ok, skipping...${x}"
+						echo
+					fi
+				fi
+
+				if [ "${activate_le_proceed:-null}" = "y" ] || [ "${activate_le_proceed:-null}" = "o" ]
+				then
+
+					hostname="$this_site"
+
+					declare -a dnsarray=(
+			                        "hostname"
+			                        )
+
+					# Skip IPv6 checks as EasyEngine doesn't yet support it [WTF!!!]
+
+					declare -a iparray=(
+			                        "v4"
+			                        )
+
+					declare -A digarray=(
+						[HN]=""
+						[www]="www."
+					)
+
+					dnschecktype=$hostname
+					thisipv4="$(dig +short myip.opendns.com @resolver1.opendns.com)"
+
+					for dnstype in "${dnsarray[@]}"
+				        do
+
+				        	for ipversion in "${iparray[@]}"
+				        	do
+
+		        				echo "${b}   Now let's make sure your site's IP$ipversion DNS settings are correct.${x}"
+		        				echo
+
+			        			digarrayiter=0
+
+			        			for i in "${!digarray[@]}"
+			        			do
+
+			        				digarrayiter=$((digarrayiter + 1))
+
+		        					echo "${b}   $digarrayiter] Now checking the ${digarray[$i]}$dnschecktype DNS record in IP$ipversion...${x}"
+		        					echo
+
+			        				accept=n
+			        				until [ $accept = "y" ]
+			        				do
+
+		        						if [ "$ipversion" = "v4" ]
+		        						then
+		        				                	thisip=$thisipv4
+		        							digresult="$(getent ahostsv4 "${digarray[$i]}""$dnschecktype". | head -1 |sed 's/ .*//')"
+		        				                	rectype="A"
+		        						else
+		        				                	thisip=$thisipv6
+		        				                	digresult="$(getent ahostsv6 "${digarray[$i]}""$dnschecktype". | grep -v "$thisipv4" | head -1 | sed 's/ .*//')"
+		        				                	rectype="AAAA"
+		        						fi
+
+			        					if [ -z "$digresult" ]
+			        					then
+
+			        						if [ ! "$dnstype" = "SRV" ]
+			        						then
+			        							echo "${r}${b}   The ${digarray[$i]}$dnschecktype IP$ipversion DNS record does NOT appear to be at all set.${x}"
+			        							echo
+			        						else
+			        							echo "${r}${b}   The ${digarray[$i]}$dnschecktype SRV record does NOT appear to be at all set.${x}"
+			        							echo
+			        						fi
+
+			        						echo "${b}   Please ensure you set your DNS record as follows:${x}"
+			        						echo
+			        						echo -e "   | ${digarray[$i]}$dnschecktype\\t\\t$rectype\\t$thisip |"
+			        						echo
+			        						if [ ! "${digarray[$i]}$dnschecktype" = "$hostname" ]
+			        						then
+			        							if [ $rectype = "A" ] || [ $rectype = "AAAA" ]
+			        							then
+			        								if [ "$ipversion" = "v4" ]
+			        								then
+			        									echo "${g}${b}   You can also set this record as a CNAME [suggested choice]:${x}"
+			        									echo
+			        									echo -e "   | ${digarray[$i]}$dnschecktype\\t\\tCNAME\\t$hostname |"
+			        									echo
+			        								fi
+			        							fi
+			        						fi
+			        						result=notset
+			        					else
+			        						if [ "$digresult" = "$thisip" ]
+			        						then
+
+			        							if [ ! "$dnstype" = "SRV" ]
+			        							then
+			        								echo "${g}${b}   The ${digarray[$i]}$dnschecktype IP$ipversion DNS record appears to resolve correctly to this server.${x}"
+			        								echo
+			        							else
+			        								echo "${g}${b}   The ${digarray[$i]}$dnschecktype SRV record appears to resolve correctly to this server.${x}"
+			        								echo
+			        							fi
+
+			        							echo -e "   | ${digarray[$i]}$dnschecktype\\t\\t$rectype\\t$thisip |"
+			        							echo
+			        							result=ok
+			        						else
+
+			        							if [ ! "$dnstype" = "SRV" ]
+			        							then
+			        								echo "${r}${b}   The ${digarray[$i]}$dnschecktype IP$ipversion DNS record does NOT appear to correctly resolve to this server.${x}"
+			        								echo
+			        							else
+			        								echo "${r}${b}   The ${digarray[$i]}$dnschecktype SRV record does NOT appear to correctly resolve to this server.${x}"
+			        								echo
+			        							fi
+
+			        							echo "${b}   This is the result of a DNS query for ${digarray[$i]}$dnschecktype:${x}"
+			        							echo
+			        							echo "   $digresult"
+			        							echo
+			        							echo "${b}   Please set it instead to:${x}"
+			        							echo
+			        							echo -e "   | ${digarray[$i]}$dnschecktype\\t\\t$rectype\\t$thisip |"
+			        							echo
+			        							if [ ! "${digarray[$i]}$dnschecktype" = "$hostname" ]
+			        							then
+			        								if [ $rectype = "A" ] || [ $rectype = "AAAA" ]
+			        								then
+			        									if [ "$ipversion" = "v4" ]
+			        									then
+			        										echo "${g}${b}   You can also set this record as a CNAME [suggested choice]:${x}"
+			        										echo
+			        										echo -e "   | ${digarray[$i]}$dnschecktype\\t\\tCNAME\\t$hostname |"
+			        										echo
+			        									fi
+			        								fi
+			        							fi
+			        							result=incorrect
+			        						fi
+			        					fi
+
+			        					if [ ! $result = "ok" ]
+			        					then
+
+										if [ "${activate_le_proceed:-null}" = "y" ]
+										then
+
+											valid=n
+				        						until [ $valid = "y" ]
+				        						do
+				        							read -n 1 -rp "${b}   Test again?${x} (${b}Y${x}[es]/${b}s${x}[kip]/${b}e${x}[xit]) " answer;
+				        							case $answer in
+				        							"")
+				        								echo
+				        								valid=y
+				        								accept=n
+				        								;;
+				        							y)
+				        								echo -e "\\n"
+				        								valid=y
+				        								accept=n
+				        								;;
+				        							s)
+				        								echo -e "\\n"
+				        								echo "${b}   Skipping DNS check for this record...${x}"
+				        								echo
+				        								valid=y
+				        								accept=y
+				        								;;
+				        							e)
+				        								echo -e "\\n"
+				        		        					echo "${b}   Exiting...${x}"
+				        		        					echo
+				        		        					exit
+				        		        					;;
+				        							*)
+				        								echo -e "\\n"
+				        								echo "${b}   Invalid option. Retry...${x}"
+				        		        					echo
+				        								valid=n
+				        								accept=n
+				        				        			;;
+				        							esac
+				        						done
+
+										else
+
+											echo "${r}${b}   DNS test failed for this record. Continuing anyway...${x}"
+											echo
+											accept=y
+
+										fi
+
+									else
+
+			        						accept=y
+
+			        					fi
+
+			        				done
+
+							if [ $result = ok ]
+							then
+
+								if [ $i = "HN" ]
+								then
+									le_dns_check_HN=ok
+								else
+									le_dns_check_www=ok
+								fi
+
+							fi
+
+			        			done
+
+	        				echo "${b}   Finished checking your $dnstype IP$ipversion DNS settings.${x}"
+	        				echo
+
+				        	done
+
+				        done
+
+					if [ "${le_dns_check_HN:-null}" = "ok" ] && [ "${le_dns_check_www:-null}" = "ok" ]
+					then
+						echo "${g}${b}   Activating LetsEncrypt for $this_site...${x}"
+						echo
+						ee site update $this_site --le --experimental || true
+					else
+						echo "${r}${b}   One or more DNS checks for $this_site failed and was skipped.${x}"
+						echo
+						echo "${b}   NOT activating LetsEncrypt for $this_site."
+						echo
+					fi
+
+					if [ ! -z "${le_dns_check_HN-}" ]
+					then
+					        unset le_dns_check_HN
+					fi
+
+					if [ ! -z "${le_dns_check_www-}" ]
+					then
+					        unset le_dns_check_www
+					fi
+
+					if [ ! -z "${activate_le_proceed-}" ]
+					then
+					        unset activate_le_proceed
+					fi
+
+				fi
 
 				echo "${b}   Finished restore for | $this_site |.${x}"
 				echo
