continue rewrite for synthia v4, support ee local-db, php --with db sites

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -81,7 +81,7 @@ synthia-define_vars() {
 	### ########################################################################
 
 	#### set default backup paths.
-	### [absolute, mark whether existing or generated].
+	#### [absolute, mark whether existing or generated].
 
 	declare -gA backup_paths_default_array=(
 		[/opt/easyengine/sites]="existing"
@@ -146,10 +146,10 @@ synthia-download_dna() {
 
 	else
 
-	if [ -d "${clone_dir}" ]
-	then
-		rm -r "${clone_dir:?}"
-	fi
+		if [ -d "${clone_dir}" ]
+		then
+			rm -r "${clone_dir:?}"
+		fi
 
 		( cd "${clone_base_dir}" && git clone "${clone_host}/${clone_author}/${clone_name}" && echo && cd "${clone_name}"
 
@@ -217,7 +217,7 @@ synthia-download_dna() {
 
 			echo "${dna_selected_vers}" > "./version_installed"
 
-	)
+		)
 
 	fi
 
@@ -232,35 +232,94 @@ synthia-source_dna() {
 
 }
 
-################################################################################
+#### ###########################################################################
 
-################################################################################
-######################## Insert project functions here #########################
-################################################################################
+#### backup_restore_functions
 
-synthia-backup_data() {
+synthia-backup() {
+
+	### evaluate arguments.
+
+	### ########################################################################
+
+    while getopts ":lsri" arguments
+		do
+			case $arguments in
+				l)	export backup_locally_only="y"
+					;;
+				s)	export backup_s3_only="y"
+					;;
+				r)	export backup_last_before_restore="y"
+					;;
+				i)	export backup_skip_install_complete_check="y"
+					;;
+				\?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
+			        dna-exit
+			        ;;
+			esac
+		done
+    OPTIND=1
+
+	if [ -n "${backup_last_before_restore-}" ]
+	then
+
+		if [ -n "${backup_s3_only-}" ]
+		then
+
+			dna-echo -e "Option | ${n-}backup_s3_only [-s]${r-} | is incompatible with option | ${n-}backup_last_before_restore [-r]${r-} |."
+			dna-exit
+
+		fi
+
+		export backup_locally_only="y"
+
+	fi
+
+	### ########################################################################
+
+	dna-backup_check_set_lockfile
+
+	if ! dna-backup
+	then
+
+		dna-echo -e "backup function exited with errors."
+		dna-echo -m "continuing anyway to perform post-backup operations if any and exit backup function gracefully."
+
+		synthia-backup_post_operations
+
+	fi
+
+	dna-backup_cleanup
+
+}
+
+synthia-backup_old() {
+
+	### evaluate arguments.
+
+	### ########################################################################
 
 	backup_excluded_sites="${backup_excluded_sites_default} ${backup_excluded_sites_custom}"
 
 	backup_excluded_sites_array=$(echo ${backup_paths_default} | tr " " "\n")
 
-	for site in $ee_www_dir/*
+    while getopts ":lsri" arguments
 	do
 
 		if [ -d "$site" ]
 		then
 
-			this_site="$(echo "$site" | sed "s|${ee_www_dir}/||")"
+			this_site_name="$(echo "$site" | sed "s|${ee_www_dir}/||")"
 
-			if ! dna-check_if_array_contains $this_site "${backup_excluded_sites_array}"
+			if ! dna-check_if_array_contains $this_site_name "${backup_excluded_sites_array}"
 			then
 
-				dna-echo -m "*] Now evaluating site: | ${g}$this_site${n-} |:"
+				dna-echo -m "*] Now evaluating site: | ${g}$this_site_name${n-} |:"
 
 				## determine target backup directory for this site.
 
-				this_site_dir="${backup_tmp_dir}/data/${this_site}"
-				mkdir -p "${this_site_data_dir}"
+				this_site_target_dir="${backup_tmp_dir}/data/${this_site_name}"
+				mkdir -p "${this_site_name_data_dir}"
 
 				## determine whether this is a wp site.
 
@@ -277,9 +336,9 @@ synthia-backup_data() {
 					wp_db_user="(cat ${wp_config_file_path} | grep DB_USER | cut -d \' -f 4"
 					wp_db_pass="(cat ${wp_config_file_path} | grep DB_PASSWORD | cut -d \' -f 4"
 
-					mysqldump -u "${wp_db_user}" -p"${wp_db_pass}" "${wp_db_name}" > "${this_site_dir}/mysqldump.sql"
+					mysqldump -u "${wp_db_user}" -p"${wp_db_pass}" "${wp_db_name}" > "${this_site_target_dir}/mysqldump.sql"
 
-					cp "${wp_config_file_path}" "${this_site_dir}/wp-config.php"
+					cp "${wp_config_file_path}" "${this_site_target_dir}/wp-config.php"
 
 				else
 
@@ -291,13 +350,13 @@ synthia-backup_data() {
 
 				## backup htdocs dir.
 
-				rsync -aAXxL "${site}/app" "${this_site_dir}"
+				rsync -aAXxL "${site}/app" "${this_site_target_dir}"
 
-				dna-echo -s "   Finished backup for | ${n-}${this_site}${g-} |."
+				dna-echo -s "   Finished backup for | ${n-}${this_site_name}${g-} |."
 
 			else
 
-			dna-echo -m "*] Site | ${r-}${this_site}${n-} | is on the exclusion list."
+			dna-echo -m "*] Site | ${r-}${this_site_name}${n-} | is on the exclusion list."
 			dna-echo -e "Skipping..."
 
 		fi
@@ -308,67 +367,191 @@ done
 
 }
 
-synthia-backup_locally() {
+#### ###########################################################################
 
-  ### Copy conf dir to $backup_tmp_dir
+### ############################################################################
 
-	cp -r "${conf_dir}" "${backup_tmp_dir}/conf/"
+### 2 | synthia project-specific functions.
 
-	### Add hardcoded sites to exclude to the user-specified ones
+### ############################################################################
 
-	backup_exclude_sites="22222, html, roundcubemail, ${backup_exclude_sites}"
+#### backup / restore.
+
+#### ###########################################################################
+
+synthia-backup_pre_operations() {
+
+	### perform pre-backup operations.
+
+	dna-echo_operation -h "performing pre-backup operations"
+
+	### ########################################################################
+	### ########################################################################
+
+	dna-echo_operation -t
+
+}
+
+synthia-backup_post_operations() {
+
+	dna-echo_operation -h "performing post-backup operations"
+
+	### perform post-backup operations.
+
+	### ########################################################################
+	### ########################################################################
+
+	dna-echo_operation -t
+
+}
+
+synthia-calculate_backup_size() {
+
+	### ########################################################################
+
+	### calculate backup_paths size.
+
+	dna-calculate_backup_paths_size
+
+	### ########################################################################
+
+	### calculate any additional custom size.
+
+	### ########################################################################
+
+	
+
+	### ########################################################################
+
+	### add it up.
+
+	backup_total_size_estimate="$((${backup_paths_size_estimate} + ${patroni_ejabberd_db_size}))"
+
+	### ########################################################################
+
+}
+
+synthia-backup_generate_additional_paths() {
+
+	### generate backups for any additional custom item by populating their
+	### respective backup_paths.
+
+	dna-echo_operation -h "backing up any additional custom backup_path"
+
+	### ########################################################################
+
+	### create paths
+
+	dna-backup_generate_additional_paths_dirs
+
+	### ########################################################################
+
+	### perform backups of every item individually
+
+	### ########################################################################
+
+	### add hardcoded sites to exclude to the user-specified ones
+
+	backup_exclude_sites="22222, html, roundcubemail, ${backup_exclude_sites_userdefined}"
 
 	### For every site...
 
-	for site in $ee_www_dir/*
+	for this_site_path in $ee_www_dir/*
 	do
+		
+		#########
+		
+		this_site_nginx_container_name="$(echo ${this_site_name} | tr -d '.')"
+		export this_site_nginx_container_id="$(docker ps -a -q --filter="name=^${this_site_nginx_container_name}_nginx")"
+		export this_site_db_container_id="$(docker ps -a -q --filter="name=${this_site_nginx_container_name}_db")"
 
-		if [ -d "$site" ]
+		#########
+
+		if [ -d "$this_site_path" ]
 		then
 
-			this_site="$(echo "$site" | sed "s|${ee_www_dir}/||")"
+			this_site_name="$(echo "$this_site_path" | sed "s|${ee_www_dir}/||")"
 
-			### If this site is not on the exclusion list...
+			### if this site is not on the exclusion list...
 
-			if [ "${backup_exclude_sites/$this_site}" = "${backup_exclude_sites}" ]
+			## fix this with an appropriate all line and only full line search with grep
+
+			if [ "${backup_exclude_sites/$this_site_name}" = "${backup_exclude_sites}" ]
 			then
 
-				dna-echo -m "*] Now evaluating site: | ${g}$this_site${n-} |:"
+				dna-echo -m "*] Now evaluating site: | ${g}$this_site_name${n-} |:"
 
-				### Determine nginx and db docker containers for this EE site
+				### determine nginx and db docker containers for this ee site
 
-				this_site_nginx_container_name="$(echo ${this_site} | tr -d '.')"
+				this_site_nginx_container_name="$(echo ${this_site_name} | tr -d '.')"
 
-        export ee_nginx_container_id="$(docker ps -a -q --filter="name=^${this_site_nginx_container_name}_nginx")"
+        		export this_site_nginx_container_id="$(docker ps -a -q --filter="name=^${this_site_nginx_container_name}_nginx")"
 
-				### Determine target backup directory for this site
+				### determine target backup directory for this site
 
-				this_site_dir="${backup_tmp_dir}/data/${this_site}"
-				mkdir -p "${this_site_dir}"
+				this_site_target_dir="${backup_tmp_dir}/data/${this_site_name}"
+				mkdir -p "${this_site_target_dir}"
 
-				wp_config_file_path="${site}/app/wp-config.php"
-
-				### If a wp-config file is found...
-
+				### determine site type
+				
+				this_site_wp_config_file_path="${this_site_path}/app/wp-config.php"
+				
 				if [ -f $wp_config_file_path ]
 				then
+					this_site_type="wp"
+				elif /usr/local/bin/ee site info "${this_site_name}" | grep -q "db"
+				then
+					this_site_type="db"
+				else
+					this_site_type="simple"
+				fi
+				
+				### determine db container if applicable			
 
-					### This is a wp site
+				if [ ! "${this_site_type}" = "simple" ]
+				then
+					
+					# db container in eev4 is now "global-db" for all sites except where specifically requested during site creation.
+					# first test if the site has a local-db container
+
+					export this_site_db_container_id="$(docker ps -a -q --filter="name=${this_site_nginx_container_name}_db")"
+					
+					if [ -z "${this_site_db_container_id-}" ]
+					then
+						
+						# local container doesn't exist, fetch the id to "global-db"
+
+						export this_site_db_container_id="$(docker ps -a -q --filter="name=global-db")"
+						
+					fi
+					
+				fi
+
+				if [ "${this_site_type}" = "wp" ]
+				then
 
 					dna-echo -m "   Proceeding with ${l-}wordpress${n-} site backup..."
-
-					### DB container is apparently the same one for all sites now.
-					### export ee_db_container_id="$(docker ps -a -q --filter="name=${this_site_nginx_container_name}_db")"
-					export ee_db_container_id="$(docker ps -a -q --filter="name=global-db")"
 
 					wp_db_name=`cat $wp_config_file_path | grep DB_NAME | cut -d \' -f 4`
 					wp_db_user=`cat $wp_config_file_path | grep DB_USER | cut -d \' -f 4`
 					wp_db_pass=`cat $wp_config_file_path | grep DB_PASSWORD | cut -d \' -f 4`
 
-					#mysqldump -u ${wp_db_user} -p${wp_db_pass} ${wp_db_name} > "${this_site_dir}/mysqldump.sql"
-					docker exec "${ee_db_container_id}" /usr/bin/mysqldump -u ${wp_db_user} --password=${wp_db_pass} ${wp_db_name} > "${this_site_dir}/mysqldump.sql"
+					#mysqldump -u ${wp_db_user} -p${wp_db_pass} ${wp_db_name} > "${this_site_target_dir}/mysqldump.sql"
+					
+					docker exec "${this_site_db_container_id}" /usr/bin/mysqldump -u ${wp_db_user} --password=${wp_db_pass} ${wp_db_name} > "${this_site_target_dir}/mysqldump.sql"
 
-					cp "${wp_config_file_path}" "${this_site_dir}/wp-config.php"
+					# implement local-db option
+
+					cp "${wp_config_file_path}" "${this_site_target_dir}/wp-config.php"
+
+				elif [ "${this_site_has_db}" = "true" ]
+				then
+					
+					### this site is not wp but it has a db
+					
+					dna-echo -m "   Proceeding with ${l-}db-enabled${n-} site backup..."
+					
+					# implement db credentials extraction from "ee site info"
 
 				else
 
@@ -376,15 +559,15 @@ synthia-backup_locally() {
 
 				fi
 
-				### Backup htdocs dir
+				### backup htdocs dir
 
-				rsync -aAXxL "${site}/app" "$this_site_dir"
+				rsync -aAXxL "${this_site_path}/app" "$this_site_target_dir"
 
-				dna-echo -s "   Finished backup for | ${n-}${this_site}${g-} |."
+				dna-echo -s "   Finished backup for | ${n-}${this_site_name}${g-} |."
 
 			else
 
-				dna-echo -m "*] Site | ${r-}${this_site}${n-} | is on the exclusion list."
+				dna-echo -m "*] Site | ${r-}${this_site_name}${n-} | is on the exclusion list."
 				dna-echo -e "Skipping..."
 
 			fi
@@ -392,6 +575,60 @@ synthia-backup_locally() {
 		fi
 
 	done
+
+	### ########################################################################
+
+	dna-echo_operation -t
+
+}
+
+synthia-backup_locally() {
+	
+	dna-echo_operation -h "backing up locally"
+
+	### generate backups for any additional custom item
+
+	synthia-backup_generate_additional_paths
+
+	### backup backup paths locally.
+
+	dna-backup_locally_data_backup_paths
+
+	### backup any additional custom item.
+
+	### ########################################################################
+	### ########################################################################
+
+	dna-echo_operation -t	
+
+}
+
+synthia-restore() {
+
+	### evaluate arguments.
+
+	### ########################################################################
+
+    while getopts ":lsri" arguments
+	do
+		case $arguments in
+			l)	export backup_locally_only="y"
+				;;
+			\?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
+		        dna-exit
+		        ;;
+		esac
+	done
+    OPTIND=1
+
+	### ########################################################################
+
+	if ! dna-backup
+	then
+
+		dna-echo -e "restore function exited with errors."
+
+	fi
 
 }
 
@@ -411,17 +648,17 @@ restore_loop() {
 	for site in $restore_file_path/data/*
 	do
 
-		if [ -d "$site" ]
+		if [ -d "$this_site_path" ]
 		then
 
-			this_site="$(echo "$site" | sed "s|${restore_file_path}/data/||")"
+			this_site_name="$(echo "$this_site_path" | sed "s|${restore_file_path}/data/||")"
 
-			if [ "${restore_exclude_sites/$this_site}" = "$restore_exclude_sites" ]
+			if [ "${restore_exclude_sites/$this_site_name}" = "$restore_exclude_sites" ]
 			then
 
-				echo "${b}*] Now evaluating site | ${g}$this_site${x}${b} |: ${x}"
+				echo "${b}*] Now evaluating site | ${g}$this_site_name${x}${b} |: ${x}"
 				echo
-				www_site_dir="$www_dir/$this_site"
+				www_site_dir="$www_dir/$this_site_name"
 
 				proceed=y
 
@@ -435,7 +672,7 @@ restore_loop() {
 					then
 						echo "${b}   Deleting site and re-creating it restoring its respective backup...${x}"
 						echo
-						ee site delete $this_site --no-prompt
+						ee site delete $this_site_name --no-prompt
 					else
 
 						read -rp "${b}   Delete it and re-create it restoring its respective backup? (Y/n): ${x}" -n 1
@@ -444,7 +681,7 @@ restore_loop() {
 						then
 							echo "${b}   Ok, proceeding...${x}"
 							echo
-							ee site delete $this_site --no-prompt
+							ee site delete $this_site_name --no-prompt
 						else
 							echo
 							echo "${b}   Ok, skipping...${x}"
@@ -458,7 +695,7 @@ restore_loop() {
 				if [ $proceed = y ]
 				then
 
-					ee site create $this_site
+					ee site create $this_site_name
 					echo
 
 					### Test to see if site to be restored is a wordpress site and if it is restore it while replacing new database details
@@ -470,7 +707,7 @@ restore_loop() {
 						echo "${b}   Proceeding with ${l}wordpress${x}${b} site restore...${x}"
 						echo
 
-						ee site update $this_site --wpfc
+						ee site update $this_site_name --wpfc
 						echo
 
 						www_wp_config_file="$www_site_dir/wp-config.php"
@@ -502,7 +739,7 @@ restore_loop() {
 
 							echo "${b}   Activating PHP on this site...${x}"
 							echo
-							ee site update $this_site --php
+							ee site update $this_site_name --php
 							echo
 
 						elif [ "${enable_php:-null}" = "n" ]
@@ -518,7 +755,7 @@ restore_loop() {
 							then
 								echo "${b}   Ok, proceeding...${x}"
 								echo
-								ee site update $this_site --php
+								ee site update $this_site_name --php
 								echo
 								echo
 							else
@@ -531,7 +768,7 @@ restore_loop() {
 
 					fi
 
-					rsync -aAXx --exclude wp-config.php --exclude mysqldump.sql "$site"/ "$www_site_dir"
+					rsync -aAXx --exclude wp-config.php --exclude mysqldump.sql "$this_site_path"/ "$www_site_dir"
 
 					chown -R www-data:www-data "$www_site_dir"
 
@@ -567,7 +804,7 @@ restore_loop() {
 					if [ "${activate_le_proceed:-null}" = "y" ] || [ "${activate_le_proceed:-null}" = "o" ]
 					then
 
-						hostname="$this_site"
+						hostname="$this_site_name"
 
 						declare -a dnsarray=(
 						"hostname"
@@ -786,14 +1023,14 @@ restore_loop() {
 
 						if [ "${le_dns_check_HN:-null}" = "ok" ] && [ "${le_dns_check_www:-null}" = "ok" ]
 						then
-							echo "${g}${b}   Activating LetsEncrypt for $this_site...${x}"
+							echo "${g}${b}   Activating LetsEncrypt for $this_site_name...${x}"
 							echo
-							ee site update $this_site --le --experimental || true
+							ee site update $this_site_name --le --experimental || true
 							echo
 						else
-							echo "${r}${b}   One or more DNS checks for $this_site failed and was skipped.${x}"
+							echo "${r}${b}   One or more DNS checks for $this_site_name failed and was skipped.${x}"
 							echo
-							echo "${b}   NOT activating LetsEncrypt for $this_site."
+							echo "${b}   NOT activating LetsEncrypt for $this_site_name."
 							echo
 						fi
 
@@ -814,14 +1051,14 @@ restore_loop() {
 
 					fi
 
-					echo "${b}   Finished restore for | $this_site |.${x}"
+					echo "${b}   Finished restore for | $this_site_name |.${x}"
 					echo
 
 				fi
 
 			else
 
-				echo "${b}*] Site | ${r}$this_site${x}${b} | is on the exclusion list.${x}"
+				echo "${b}*] Site | ${r}$this_site_name${x}${b} | is on the exclusion list.${x}"
 				echo
 				echo "${b}   Skipping...${x}"
 				echo
@@ -1006,7 +1243,7 @@ synthia-perform_installation() {
 
 	}
 
-	dna-set_option -o "backup_exclude_sites" -p "backups/local" -d "y" -v "n"
+	dna-set_option -o "backup_exclude_sites_userdefined" -p "backups/local" -d "y" -v "n"
 
 	dna-add_cron_job -n "${project_name}-backup" -t "8 4 * * * " -c "bash ${tools_dir}/${project_name}-backup"
 
