update backup tool for synthia v4

diff --git a/tools/raptor-backup b/tools/raptor-backup
--- a/tools/raptor-backup
+++ b/tools/raptor-backup
@@ -1,22 +1,42 @@
 #!/usr/bin/env bash
 
-################################################################################
+### ############################################################################
 
-### Set bash environment error management
+### initialize script with standard synthia bootstrapping block.
 
-set -eu
+### ############################################################################
 
-################################################################################
-
-### Add padding to output
+#### 1 | add padding to output / clear screen.
 
 echo
 
-################################################################################
+#### 2 | locate execution environment and perform synthia-bound operations.
 
-### Determine script execution directory and install directory.
+#### ###########################################################################
 
-exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+##### set bash environment error management.
+
+set -eu
+
+##### determine script execution directory and install directory.
+
+if [ -L "${BASH_SOURCE}" ]
+then
+
+    ###### this file is being executed via a symlink.
+    ###### therefore identify the parent directory of the target file.
+
+    link_target="$(readlink ${BASH_SOURCE})"
+    exec_dir="${link_target%/*}"
+
+else
+
+    ###### this file is being directly executed.
+    ###### therefore identify our parent directory.
+
+    exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+fi
 
 exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
 exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"
@@ -37,168 +57,91 @@ else
 	fi
 fi
 
-### Source local functions file.
+##### source local functions file.
 
 . "$exec_dir_root/functions"
 
-################################################################################
-
-### Define formatting
+##### define formatting.
 
 synthia-define_formatting
 
-################################################################################
-
-### Check for root user runtime
+##### check for root user runtime.
 
 synthia-check_root
 
-################################################################################
+#### ###########################################################################
 
-### Source dna
+#### 3 | source dna and perform dna-bound operations.
+
+#### ###########################################################################
+
+##### source dna.
 
 synthia-source_dna
 
-################################################################################
-
-### Define variables
+##### define variables.
 
 synthia-define_vars
 
-################################################################################
-
-### Read conf settings
+##### read conf settings.
 
 dna-read_conf_settings
 
-################################################################################
+##### touch temp dir.
 
-### Log script
+dna-touch_tmp_project_dir
+
+#### ###########################################################################
+
+#### 4 | head/log script.
 
 dna-log_script
 
-################################################################################
+### ############################################################################
 
-while getopts ":s" arguments; do
+### evaluate arguments.
+
+### ############################################################################
+
+while getopts ":lsri" arguments
+do
     case $arguments in
-		s)	skip_install_complete_check="-s"
-			;;
-		\?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
-			dna-exit
-			;;
-	esac
+        l)	export backup_locally_only="y"
+            ;;
+        s)	export backup_s3_only="y"
+            ;;
+        r)	export backup_last_before_restore="y"
+            ;;
+        i)	export backup_skip_install_complete_check="y"
+            ;;
+        \?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
+            dna-exit
+            ;;
+    esac
 done
 OPTIND=1
 
-################################################################################
-
-### Check for lockfile to avoid multiple simultaneous backups
-
-if [ -f /tmp/${project_name}-backup-running-lockfile ]
+if [ -n "${backup_last_before_restore-}" ]
 then
 
-    dna-echo -e "It appears a ${project_name} backup is already running, perhaps an automated daily one, or perhaps the last one was interrupted."
-    dna-echo -m "If this *is* an automated daily one, please check that you're not running a manual one or that the last run was interrupted."
-    dna-echo -m "Running multiple simultaneous backups is absolutely not supported and will make both fail."
-
-	if [ "${interactive}" = "y" ]
+    if [ -n "${backup_s3_only-}" ]
     then
-        dna-ask_for_boolean -d "n" -q "If you're certain that another backup is NOT running, would you like to ignore the lockfile and continue?"
-        if [ "${boolean_output}" = "y" ]
-        then
-            dna-echo -m "Ok, continuing anyway..."
-            export lockfile_set="/tmp/${project_name}-backup-running-lockfile"
-        else
-            dna-echo -m "Ok, aborting..."
-            dna-exit
-        fi
 
-    else
-
-        dna-echo -m "If you're certain that another backup is NOT running, run this script manually and select to ignore the lockfile and continue when prompted."
-        dna-echo -m "Alternatively, you can also log into this machine and | ${o-}rm /tmp/${project_name}-backup-running-lockfile${n-} |."
-        dna-echo -e "Aborting backup for now."
+        dna-echo -e "Option | ${n-}backup_s3_only [-s]${r-} | is incompatible with option | ${n-}backup_last_before_restore [-r]${r-} |."
         dna-exit
 
     fi
 
-else
-
-    ### Set lockfile.
-
-    export lockfile_set="/tmp/${project_name}-backup-running-lockfile"
-    touch "${lockfile_set}"
+    export backup_locally_only="y"
 
 fi
 
-################################################################################
+### ############################################################################
 
-dna-backup_purge_incomplete_archives
+### actually start script operations.
 
-dna-backup_purge_dirs
+### ############################################################################
 
-dna-backup_create_dirs backup
+synthia-backup
 
-dna-backup_update_storage_info
-
-dna-backup_purge_backups
-
-if [ "$backup_archival_location" = "s3" ]
-then
-
-    dna-backup_restore_from_S3 test
-
-    dna-backup_purge_dirs
-
-    dna-backup_create_dirs backup
-
-fi
-
-dna-backup_locally "${skip_install_complete_check-}"
-
-################################################################################
-
-if [ "$backup_archival_location" = "s3" ]
-then
-
-    if [ "${s3_restore_test_failed-null}" = "y" ]
-    then
-
-        dna-echo -e "Skipping S3 backup because of a previous test restore failure."
-
-        rm -r "$backup_tmp_dir"
-
-    else
-
-    	mv "$backup_tmp_dir"/* "$backup_local_storage_path/latest"
-
-    	############################################################################
-
-    	dna-backup_to_S3
-
-    fi
-
-else
-
-	rm -r "$backup_tmp_dir"
-
-fi
-
-if [ -d "$backup_local_storage_path/temp" ]
-then
-	rm -r "${backup_local_storage_path:?}/temp"
-fi
-
-dna-backup_purge_dirs
-
-if [ -f "/tmp/${project_name}-backup-running-lockfile" ]
-then
-    rm "/tmp/${project_name}-backup-running-lockfile"
-fi
-
-if [ "${s3_restore_test_failed-null}" = "y" ]
-then
-    dna-exit
-fi
-
-dna-echo -s "Backup complete!"
+### ############################################################################
